In [2]:
##numpy

In [4]:
#array module

In [6]:
from array import array
my_array=('i',[2,5,7,8,6])

In [8]:
my_array 

('i', [2, 5, 7, 8, 6])

In [10]:
type(my_array)

tuple

In [12]:
#numpy arrays

In [14]:
import numpy as np


In [16]:
arr=np.array([1,2,3,4,5])

In [18]:
arr

array([1, 2, 3, 4, 5])

In [20]:
type(arr)

numpy.ndarray

In [22]:
arr.ndim

1

In [24]:
arr.dtype

dtype('int32')

In [26]:
array_new = np.array([1,2,3,4,5])

In [28]:
array_new +3

array([4, 5, 6, 7, 8])

In [30]:
type(array_new)

numpy.ndarray

In [32]:
my_numpy_array=np.array([1,2,3,4,5])

In [34]:
new_array=my_numpy_array*3

In [36]:
new_array

array([ 3,  6,  9, 12, 15])

In [38]:
type(new_array)

numpy.ndarray

In [40]:
type(my_numpy_array)

numpy.ndarray

In [42]:
new_array>5

array([False,  True,  True,  True,  True])

In [44]:
matrix=np.array([
    [1,2,3],
    [4,3,5],
    [3,7,9]])


In [46]:
matrix

array([[1, 2, 3],
       [4, 3, 5],
       [3, 7, 9]])

In [48]:
arr_2d=np.array([[0,1,2],[3,4,5],[7,9,8]])

In [50]:
arr_2d*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [14, 18, 16]])

In [52]:
type(arr_2d)

numpy.ndarray

In [54]:
arr_2d.ndim

2

In [56]:
arr_2d+2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 9, 11, 10]])

In [58]:
arr_2d-1

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 6,  8,  7]])

In [60]:
arr_2d%2


array([[0, 1, 0],
       [1, 0, 1],
       [1, 1, 0]], dtype=int32)

In [62]:
list_data = [1,6,5,7,9]
array_from_list=np.array(list_data)

In [64]:
list_data


[1, 6, 5, 7, 9]

In [66]:
type(list_data)

list

In [68]:
array_from_list

array([1, 6, 5, 7, 9])

In [70]:
type(array_from_list)

numpy.ndarray

In [72]:
array_from_list

array([1, 6, 5, 7, 9])