In [ ]:
#creating numpy array

In [2]:
import numpy as np

In [4]:
a= np.ones((3,4))

In [6]:
type(a)


numpy.ndarray

In [8]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
a1=np.zeros((2,4))

In [12]:
a1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
zeros_array=np.zeros((3,3))

In [22]:
ones_array=np.ones((2,4))

In [24]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
identity_matrix=np.eye(3)

In [30]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
b=[1,2,3,4]

In [34]:
np.array(b,dtype=np.int32)

array([1, 2, 3, 4])

In [36]:
int_array=np.array([1,2,3], dtype=np.int32)
float_array=np.array([0.1,0.2,0.3],dtype=np.float64)

In [38]:
int_array

array([1, 2, 3])

In [40]:
float_array

array([0.1, 0.2, 0.3])

In [42]:
a2=np.arange(0,8)

In [44]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [46]:
linspace_array=np.linspace(0,10,6)

In [48]:
linspace_array

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [50]:
linspace_array1=np.linspace(0,20,5)

In [52]:
linspace_array1

array([ 0.,  5., 10., 15., 20.])

In [54]:
random_array=np.random.rand(4,4)

In [56]:
random_array

array([[0.87249489, 0.35969726, 0.75480825, 0.19159045],
       [0.34440338, 0.9016489 , 0.51321141, 0.90438277],
       [0.05131257, 0.98866744, 0.42356102, 0.85401889],
       [0.12894317, 0.72991142, 0.02041393, 0.45975399]])

In [58]:
#basic indexing

In [60]:
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[-1])

10
40


In [62]:
arr1=np.array([[23,4,6,3],[1,67,98,6]])

In [64]:
arr1

array([[23,  4,  6,  3],
       [ 1, 67, 98,  6]])

In [66]:
print(arr1[0,3])

3


In [68]:
print(arr1[1,-1])

6


In [70]:
#1D array slicing

In [72]:
arr2=np.array([1,7,8,5,4,3])
print(arr2[1:4])
print(arr2[:6])
print(arr2[:-1])

[7 8 5]
[1 7 8 5 4 3]
[1 7 8 5 4]


In [74]:
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [76]:
print(matrix[0:1,1:3])

[[2 3]]


In [78]:
print(matrix[2:3,1:2])

[[8]]


In [80]:
print(matrix[1:2,1:3])

[[5 6]]


In [82]:
v=np.array([1,2,3,4])

In [84]:
s=v[1:3]

In [86]:
s

array([2, 3])

In [88]:
#copy

In [90]:
a=np.array([1,2,3,4,5])

In [92]:
b=a[1:3].copy()

In [94]:
b

array([2, 3])

In [96]:
#shape

In [98]:
arr=np.array([[1,2,3],[4,5,6]])

In [100]:
arr.shape

(2, 3)

In [102]:
a=np.arange(12)

In [104]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [106]:
b=a.reshape(3,4)

In [108]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
d=np.arange(20)

In [112]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [114]:
e=d.reshape(5,4)

In [116]:
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [118]:
arr_3d=np.array([[0,1,2],
              [4,5,6],
              [7,8,9]])

In [120]:
arr_3d.transpose()

array([[0, 4, 7],
       [1, 5, 8],
       [2, 6, 9]])

In [122]:
arr=np.array([[1,2,3,4,5,6],[10,20,30,40,50,60]])

In [124]:
arr.transpose()

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50],
       [ 6, 60]])