In [1]:
import numpy as np

In [21]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[5,7]])

In [23]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 5, 7]])

In [29]:
arr3=np.array([1,2,3])
arr4=np.array([4,5,6])
 

In [ ]:
###stack arrays vertically(row-wise)

In [31]:
np.vstack((arr3,arr4))

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a=np.array([1,2])
b=np.array([3,4])

In [35]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [37]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
mask=arr>3
filtered=arr[mask]
print("Filtered elements(greater than 3):",filtered)

Filtered elements(greater than 3): [4 5 6]
