In [1]:
import numpy as np

In [21]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[5,7]])

In [23]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 5, 7]])

In [29]:
arr3=np.array([1,2,3])
arr4=np.array([4,5,6])
 

In [ ]:
###stack arrays vertically(row-wise)

In [31]:
np.vstack((arr3,arr4))

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a=np.array([1,2])
b=np.array([3,4])

In [35]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [29]:
import numpy as np
aa=np.array([1,2,3,4,5,6])
mask=aa>3
filtered=aa[mask]
print("Filtered elements(greater than 3):",filtered)

Filtered elements(greater than 3): [4 5 6]


In [31]:
(aa>2)&(aa<6) #-------boolean

array([False, False,  True,  True,  True, False])

In [33]:
aa[(aa>2)&(aa<6)]    #------filtered

array([3, 4, 5])

In [35]:
aa[(aa<=3) | (aa>5)]

array([1, 2, 3, 6])

In [37]:
matrix=np.array([
    [10,15,20,],
    [25,30,35]
])
print("Values > 20:",matrix[matrix>20])

Values > 20: [25 30 35]


In [39]:
scores=np.array([85,92,78,88,95,72,89,94,68,90])

In [41]:
print("Scores values>90:",scores[scores>90])

Scores values>90: [92 95 94]


In [43]:
scores[(scores>70)  | (scores<80)]

array([85, 92, 78, 88, 95, 72, 89, 94, 68, 90])

In [45]:
import numpy as np


In [47]:
ab=np.arange(1,16)

In [49]:
ab

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
ab[ab%3==0]    #------numbers that rae divisible by 3

array([ 3,  6,  9, 12, 15])

In [53]:
ab[ab%2==0]    #----even numbers

array([ 2,  4,  6,  8, 10, 12, 14])

In [55]:
ab[ab%2!=0]    #-----odd numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [57]:
import numpy as np
temp=np.array([22.5,19.0,25.6,21.4,29.9,18.6,23.1,27.0])
temp[temp>24]

array([25.6, 29.9, 27. ])

In [59]:
temp[(temp > 20)  & (temp < 26)]

array([22.5, 25.6, 21.4, 23.1])

In [61]:
prices=np.array([250,499,520,310,800,999,450,720])

In [63]:
prices[prices>500]

array([520, 800, 999, 720])